# Generated by Django 3.2.9 on 2021-12-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_dislikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('location', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaMovieShowings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('showing_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('numbers_of_tickets', models.IntegerField()),
                ('ticket_price', models.FloatField()),
                ('sold_tickets', models.IntegerField(default=0)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='movie.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='movie.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cinema',
            name='movie_showings',
            field=models.ManyToManyField(related_name='cinemas', through='movie.CinemaMovieShowings', to='movie.Movie'),
        ),
        migrations.AlterUniqueTogether(
            name='cinema',
            unique_together={('name', 'location')},
        ),
    ]
