# Generated by Django 3.2.9 on 2021-12-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20211202_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemamovieshowings',
            name='sales_open',
            field=models.BooleanField(default=True),
        ),
    ]
