# Generated by Django 3.2.9 on 2021-12-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_cinemamovieshowings_sales_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='finances',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cinemamovieshowings',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
